Return to [[./README.org][Main Page]].
(Would be nice to pretty this up.)


** Current Graduate Students 
- Craig Waitt (First-Principles Free Energy Calculations)
- Anshuman Goswami (KMC simulation of heterogeneous catalytic reactions)
- Neha Mehra (Zeolites for Hydrocarbon Oligomerization)
- Wei Ge (Catalysis in Zeolites)
- Xuyao Gao (Catalysis in Zeolites)
- Chuang Yan (Nitrogen Plasma Catalysis)
- Amish Chovatiya (Ammonia Oxidation Kinetics)
- Denver Haycock (Plasma Catalysis)
- Jose Rebolledo Oyarce (Catalysis in Zeolites)
- Raghav Saxena (Catalysis in Zeolites)


** Former M.Sc. Students
- 5 :: Solomon Assefa, ",", April 2016.
- 4 :: Steven McDonough, M.Sc.\nbsp{}Thesis "Using Through-Space, Dipole-Dipole, and CO-d-band Interactions to Predict the Formation Energy of CO/Pd(111) Configurations," February 2015.
- 3 :: Michelle Morton, M.Sc.\nbsp{}Thesis, "Effects Of Nitrogen Based Anions On CO2 Binding And Proton Affinity," May 2013.
- 2 :: Mandelle Danser, M.Sc.\nbsp{}Thesis "Beyond the Gas Phase: Towards Modeling Bulk Ionic Liquids with a Comparison of Density Functional Tight Binding  (DFTB) to Density Functional Theory (DFT)," December 2010.
- 1 :: Wenguang Lin, M.Sc.\nbsp{}thesis "DFT Simulations of \ce{Re_3} Metal Cluster Binding on Alumina in Hydrogen Environments," December 2008.

** Former Ph.D. Students
- 12 :: Dr.\nbsp{}Quintin Sheridan, "Simulation Study of CO2-Reactive Aprotic Heterocyclic Anion Ionic Liquids: Water Interactions, Liquid Structure, and CO2 Solubility," [[https://curate.nd.edu/show/44558c99p04]], April 2017.
- 11 :: Dr.\nbsp{}Christopher Paolucci, "Theoretical and Computational Modeling of the Selective Catalytic Reduction of NOx in Cu-SSZ-13 Zeolites," [[https://curate.nd.edu/show/r781wd39s26]], April 2017.
- 10 :: Dr.\nbsp{}Laura Herder, "Nucleation of Surface Platinum Oxide on Pt(111)," August 2015.  Currently UW-Lacrosse.
- 9 :: Dr.\nbsp{}Trunojoyo Anggara, "First-Principles Study of NO Oxidation on Cu-Exchanged SSZ-13 Zeolite Catalysts," August 2015. Currently Notre Dame.
- 8 :: Dr.\nbsp{}Michael Penninger, "Simulation of NO Oxidation Catalysis on Perovskite Catalysts," May 2015. Currently UOP.
- 7 :: Dr.\nbsp{}John Clay, "Comparison Of Palladium And Platinum Water Gas Shift Reaction Kinetics Using Density Functional Theory Models," August 2014.  ERC, Incorporated.
- 6 :: Dr.\nbsp{}Dorrell McCalman, Dissertation "Simulation of Aqueous Phase NOx Reduction over Pd Catalysts," April 2013.
- 5 :: Dr.\nbsp{}Jason M.\nbsp{}Bray, Dissertation "Adsorbate Coverage Dependence In Heterogeneous Catalysis: Kinetics Of Oxygen Adsorption On Platinum Surfaces From First Principles," April 2013.  Currently Phillips 66.
- 4 :: Dr.\nbsp{}David J.\nbsp{}Schmidt, Ph.D., dissertation "Cluster Expansion Studies Of Oxygen Adsorption On Transition Metal Surfaces," December 2012.
- 3 :: Dr.\nbsp{}Elaine Mindrup, Ph.D.\nbsp{}dissertation "Discovery of New Ionic Liquids for CO2 Capture," May 2011.  Currently Patent Examiner, US Patent and Trademark Office.
- 2 :: Dr.\nbsp{}Hangyao Wang, Ph.D.\nbsp{}dissertation "Simulation of Catalytic Oxidation over Transition Metal Oxides," September 2009.  Currently research scientist, Dow Chemical Company.
- 1 :: Dr.\nbsp{}Rachel Getman.  Ph.D.\nbsp{}dissertation, "First Principles Models of NO Oxidation Catalysis," May 2009.  Currently Assistant Professor, Clemson University.

** Past Post-doctoral Associates
- 16 :: Dr.\nbsp{}Onise Sharia, Bank of America
- 15 :: Dr.\nbsp{}TaeBum Lee, unaffiliated
- 14 :: Dr.\nbsp{}Kurt Frey, Institute for Disease Modeling
- 13 :: Dr.\nbsp{}Houyu Zhu, Lecturer, Tsingdao University
- 12 :: Dr.\nbsp{}Sonia Antony, unaffiliated
- 11 :: Dr.\nbsp{}Shuguang Zhang, Assoc.\nbsp{}Prof., Shandong University
- 10 :: Dr.\nbsp{}Vladimir Pomogaev, Assoc.\nbsp{}Prof., Tomsk State University
- 9 :: Dr.\nbsp{}Katie Maerzke, research scientist, Los Alamos National Lab
- 8 :: Prof.\nbsp{}Jean-Sabin McEwen, Asst.\nbsp{}Prof., Washington State University
- 7 :: Dr.\nbsp{}Zhengzheng Chen, research associate, CSU-Northridge
- 6 :: Prof.\nbsp{}Chao Wu, Xi'an Jiaotong University
- 5 :: Prof.\nbsp{}Bhabani Mallik, Asst.\nbsp{}Prof., Indian Institute of Technology Hyderabad, India
- 4 :: Dr.\nbsp{}Victor Ranea, currently Conicet Argentina.
- 3 :: Dr.\nbsp{}Abhijit Phatak, currently Intel Corp.
- 2 :: Dr.\nbsp{}Li Xiao, currently Accelrys Corp.
- 1 :: Dr.\nbsp{}Ye Xu, currently Asst.\nbsp{}Prof., Louisiana State University

** Undergraduates Supervised
Josh Bruce (CBE 2007), Jessica Nadai (CBE 2007), Shawn Coleman (CBE 2009), Nathaniel Menendez (CBE 2009), Andrea Baker (CBE 2009), Thomas Senftle (CBE 2010), Daniel Beyrer (Rose-Hulman, 2011), Miriam Shakalli Tang (CBE 2011), Martin Beres (CBE 2010), Kevin McNamara (CBE 2012), Steven Woltornist (Franciscan University, 2011), Nicklas Hjalmarsson (RIT Sweden, 2012), Mark Sullivan (CBE 2012), Jonathon Conway (CBE 2011), Jennifer Smith (CBE 2012), Ryan Anderson (CBE 2013), Allison Hamman (CBE 2012), Anna-Maria Eriksson (RIT Sweden, 2012), Brian Brady (Penn State 2014), Kate Bowie (CBE 2014), Samuel Mingos (CBE 2014), Sean Dwyer (CBE 2015), Patrick Connelly (CBE 2015), Andrew Lehmer (CBE 2017)
