Return to [[./Home.org][Schneider Group]]

* Priority Tasks
Several things need to happen when you first join the group. Most of these things should be done automatically, but final responsibility is with the individual group member.

** Administrative
- Get a seat in an office with a computer.
- Get card access to CoMSEL office from Lisa in the CBE department office.  
- Ask for a key to the interior CoMSEL rooms.
- Set up an account with the Center for Research Computing [[https://crc.nd.edu][(CRC)]].
- Contact the CRC to be added to the user list for the Schneider queues ([[CRCSupport@nd.edu][email]).
- Contact the CRC, using email above, to be put on the approved list for VASP, ADF, or whichever software you will be using.
- For Linux workstations, be added to the /etc/password list.
- For Windows workstations, set up openAFS.
- Ask Professor Schneider for access to the group AFS space: /afs/crc.nd.edu/user/w/wschnei1/Group/
- Get access to the group Windows server.
- Set up printers from CoMSEL and the Engineering library.
- Get added to the Schneider group and COMSEL supergroup mailing lists.



** Educational
If unfamiliar with Linux, the following tutorials may be helpful:
- [[http://tille.garrels.be/training/tldp/index.html]["Introduction to Linux: A Hands on Guide" by Machtelt]]
- [[http://www.linux-tutorial.info/toc][Linux Knowledge Base and Tutorial]]
- [[http://www.ee.surrey.ac.uk/Teaching/Unix/][UNIX Tutorial for Beginners]]
- [[http://lowfatlinux.com/][Free Linux training]]
- [[http://wiki.crc.nd.edu/wiki/index.php/Linux_FAQ][Linux FAQ on CRC Wiki]]
- [[http://software-carpentry.org/4_0/shell/][Youtube lecture that covers the basics of using the Unix command shell from software-carpentry]]
- [[http://wiki.crc.nd.edu/wiki/index.php/Linux_Coding_Cheat_Sheets_and_More][Links to Linux tutorials and cheat sheets]]
- [[http://lifehacker.com/5743814/become-a-command-line-ninja-with-these-time+saving-shortcuts][Becoming a command line ninja with these time-savings shortcut]]

You will also want to become familiar with emacs, org-mode, and python.


Visit [[./DFT.org][DFT basics]] page to start learning about DFT.

Sign up for [[http://wiki.crc.nd.edu/wiki/index.php/CRC_Training][CRC Training Courses]] that may be useful or of interest.

* Meetings
Group meetings are held weekly in the CoMSEL seminar area.

In addition to group meetings, group members are expected to participate in weekly supergroup meetings held in the CoMSEL seminar area. These meetings combine several of the computational groups on campus, and each graduate student is expected to present once per academic year. Supergroup meetings are not held during the summer.

Depending on your research project, you will also be assigned to a subgroup (Catalysis, Ionic Liquids, Water Gas Shift, Coverage, Perovskite, etc.). Each subgroup meets weekly for 1-2 hours to discuss each individual progress.

Graduate students are also expected to attend their respective department seminars, which take place near-weekly during the school year.
