* Welcome!
Welcome to the Schneider group information page. Additional information on the Group can be found on [[http://www.nd.edu/~wschnei1/][Bill's website]].

This repo is a collection of [[orgmode.org][org mode]] files created within [[https://www.gnu.org/software/emacs/][emacs]] and shared on [[https://github.com/wfschneidergroup/wiki][github]].  It is intended to be used as a portal for sharing information about the group. As you get more experience with all these mysterious things, contribute ("push") new information.  Contribute to making the group a better place than how you found it.

* General Information
Group correspondence can be addressed to [[mailto:SchneiderGroup-list@nd.edu][SchneiderGroup-list@nd.edu]]. Contact the current [[mailto:pmehta1@nd.edu][list manager]] for questions or concerns.


Some tips on getting started in the Group can be found on the [[./New-Group-Member.org][New-Group-Member]] page.

* Group Resources

* Meetings

* Publications
A list of published papers is available at the [[www.nd.edu/~wschnei1/Publications.shtml][Publications website]].  Also, all publications are (or at least should be) available on the group shared Google space at [[https://drive.google.com/drive/u/1/folders/0B7-2wq5AHpRENEhWeUx4ZTRLalk][GDrive/Group/Publications]].

Dissertations are available at [[https://drive.google.com/drive/u/1/folders/0B7-2wq5AHpREdkl1cDdOanhiNDg][GDrive/Group/Dissertations]].

* Policies and Procedures
** Conferences
** Publishing
** Group citizenship
** (Semi-)Annual Reports
** Work Week and Time Off
Graduate school is generally not a 40 hour a week job, at least if you hope to graduate before funding runs out. Work hard and have fun. Some people are early birds, some are night owls. Whatever the case, try to be in the office between the hours 10 am - 4 pm, when most meetings are held. The University has a number of holidays, plus you are "officially" given two weeks a year of vacation. Be courteous and let your coworkers and supervisors know when you'll be out of the office.
** Sick Leave
When you are sick, please stay home.  No one in CoMSEL is interested in sharing your germs.

* Group computers
Group computers are hosted by the [[http://crc.nd.edu][Notre Dame Center for Research Computing]].  Information on computers is available here.
