* Greetings group members, students, and guests!
Welcome to the Schneider group information page. Additional information on the Group can be found on [[http://www.nd.edu/~wschnei1/][Bill's website]].

This repository is a collection of relevant files and events happening within the Schneider's Group. In this repository, you can find [[orgmode.org][org mode]] files created within [[https://Twww.gnu.org/software/emacs/][emacs]] and shared on [[https://github.com/wfschneidergroup/wiki][github]].  This page is intended to be used as a portal for sharing information about the group. You can either read it through git or download to your own computer via [[https://desktop.github.com/][MIT-licensed Github]].  As you get more experience with all these mysterious things, contribute ("push") new/updated information to the repository.

* General Information
Group correspondence can be addressed to [[mailto:SchneiderGroup-list@nd.edu][SchneiderGroup-list@nd.edu]]. Contact the current [[mailto:pmehta1@nd.edu][list manager]] for questions or concerns.  Current and former group members are listed [[./members.org][here]].

* New Group members
Some tips on getting started in the Group can be found on the [[./New-Group-Member.org][New-Group-Member]] page.

* Group Resources
For information about computers, software, scripts, etc. used in the group, please visit [[./Resources.org][Group Resources]] page.

* Meetings
Schneider's group regularly attends the CoMSEL Supergroup meetings, as well as holding weekly Group meetings and topical Subgroup meetings. The schedule is shared on a [[https://calendar.google.com/calendar/embed?src=b3e5dnq5qj5dlmov44dplttt6s%40group.calendar.google.com&ctz=America/New_York][Google Calendar]]. Additional one-on-one meetings with Professor Schneider can be arranged as needed.

* Publications
A list of published papers is available at the [[www.nd.edu/~wschnei1/Publications.shtml][Publications website]].  Also, all publications are (or at least should be) available on the group shared Google space at [[https://drive.google.com/drive/u/1/folders/0B7-2wq5AHpRENEhWeUx4ZTRLalk][GDrive/Group/Publications]].

Dissertations are available at [[https://drive.google.com/drive/u/1/folders/0B7-2wq5AHpREdkl1cDdOanhiNDg][GDrive/Group/Dissertations]].

* Policies and Procedures
** Conferences
Group members are encouraged to present their research at conferences. Information about attending conferences can be found on the [[./Conferences.org][Conferences]] page.
** Publishing
Group members are expected to publish as part of their degree or post-doctoral work. Information about publishing in the group can be found on the [[./Publishing.org][Publishing]] page.

** Reviewing
Before a scientific paper is published, it goes through peer review.  Information on the review process can be found on the [[./Reviewing.org][Reviewing]] page.
** Group citizenship
Be nice to everyone in the group, and leave the group better than you found it.
** (Semi-)Annual Reports
At the end of (June and ) December each year Schneider would like an "accomplishments" report to use as a basis for a one-on-one discussion about research progress, future research directions, graduation plans, and post graduation plans. A Google template of the report is available [[https://docs.google.com/document/d/1iE3TTGabHms91O3ROaeS4I6eMvXUWOcUPAnLGrt7Hlg/edit][here]]. (Create a copy before typing in this!)  Someone needs to create an org version!
** Work Week and Time Off
Graduate school is generally not a 40 hour a week job, at least if you hope to graduate before funding runs out. Work hard and have fun. Some people are early birds, some are night owls. Whatever the case, try to be in the office between the hours 10 am - 4 pm, when most meetings are held. The University has a number of holidays, plus you are "officially" given two weeks a year of vacation. Be courteous and let your coworkers and supervisors know when you'll be out of the office.
** Sick Leave
When you are sick, please stay home.  No one in CoMSEL is interested in sharing your germs.

* Group computers
Group computers are hosted by the [[http://crc.nd.edu][Notre Dame Center for Research Computing]].  Information on computers is available here.

* Group software

* Group photos
We are a handsome/beautiful bunch, as documented in photos....
